services:
  - type: web
    name: success-computer-institute
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: "python server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.15
